#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the
# right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

sudo apt-get update
sudo apt-get -y install haproxy

# Edit config file for haproxy by appending
server_config= \
"
frontend emma-adu-frontend
        bind *:80
	mode http
	default_backend emma-adu-backend
backend emma-backend
        balance roundrobin
	server 313394-web-01 35.153.18.211:80 check
	server 313394-web-01 34.207.222.234:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
