#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# script should only display:
#  username
#  user id
#  Home directory path for the user

my_file="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$my_file"
